config/routes.rb
Rails.application.routes.draw do

  root 'resumes#new'
  resources :resumes

  namespace :api do
    resources :resumes, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/resume.rb
class Resume < ApplicationRecord
	has_many :educations
	has_many :experiences
  accepts_nested_attributes_for :educations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :experiences, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name
  validates_presence_of :phone
  validates_presence_of :upload_resume_or_linkedin_link
  scope :all_approved, ->{ where(approved: true) }

  #LEVELS = ["Higher Management", "Mid Management", "Others"]
  LEVELS = ["Founder / CEO","Board","CXO","VP","Director","Manager","Individual Contributor"]
  FUNCTIONS=[
              "Operations" ,"Business Development" ,"Sales","Education" ,"Engineering" ,"Information Technology" ,"Administrative" ,"Healthcare Services" ,"Arts and Design" ,"Finance" ,"Support" ,"Community and Social Services" ,"Media and Communication",
              "Accounting","Human Resources","Marketing","Program and Project Management","Research" ,"Legal","Entrepreneurship","Consulting" ,"Military and Protective Services","Real Estate","Quality Assurance","Purchasing","Product Management"
            ]
     
  INDUSTRY = [
               "Accounting","Airlines/Aviation","Alternative Dispute Resolution","Alternative Medicine","Animation","Apparel & Fashion","Architecture & Planning","Arts and Crafts","Automotive","Aviation & Aerospace",
               "Banking","Biotechnology","Broadcast Media","Building Materials","Business Supplies and Equipment",
               "Capital Markets","Chemicals","Civic & Social Organization","Civil Engineering","Commercial Real Estate","Computer & Network Security","Computer Games","Computer Hardware",
               "Computer Networking","Computer Software","Construction","Consumer Electronics","Consumer Goods","Consumer Services","Cosmetics",
               "Dairy","Defense & Space","Design","Education Management","E-Learning","Electrical/Electronic Manufacturing","Entertainment","Environmental Services","Events Services","Executive Office",
               "Facilities Services","Farming","Financial Services","Fine Art","Fishery","Food & Beverages","Food Production","Fund-Raising","Furniture",
               "Gambling & Casinos","Glass, Ceramics & Concrete","Government Administration","Government Relations","Graphic Design",
               "Health, Wellness and Fitness","Higher Education","Hospital & Health Care","Hospitality","Human Resources",
               "Import and Export","Individual & Family Services","Industrial Automation","Information Services","Information Technology and Services","Insurance","International Affairs",
               "International Trade and Development","Internet","Investment Banking","Investment Management","Judiciary",
               "Law Enforcementaw Practice","Legal Services","Legislative Office","Leisure, Travel & Tourism","Libraries","Logistics and Supply Chain","Luxury Goods & Jewelry",
               "Machinery","Management Consulting","Maritime","Marketing and Advertising","Market Research","Mechanical or Industrial Engineering","Media Production","Medical Devices",
               "Medical Practice","Mental Health Care","Military","Mining & Metals","Motion Pictures and Film","Museums and Institutions","Music","Nanotechnology","Newspapers","Nonprofit Organization Management",
               "Oil & Energy","Online Media","Outsourcing/Offshoring","Package/Freight Delivery","Packaging and Containers","Paper & Forest Products","Performing Arts","Pharmaceuticals","Philanthropy",
               "Photography","Plastics","Political Organization","Primary/Secondary Education","Printing","Professional Training & Coaching","Program Development","Public Policy","Public Relations and Communications","Public Safety","Publishing",
               "Railroad Manufacture","Ranching","Real Estate","Recreational Facilities and Services","Religious Institutions","Renewables & Environment","Research","Restaurants","Retail",
               "Security and Investigations","Semiconductors","Shipbuilding","Sporting Goods","Sports","Staffing and Recruiting","Supermarkets","Telecommunications","Textiles","Think Tanks","Tobacco",
               "Translation and Localization","Transportation/Trucking/Railroad","Utilities","Venture Capital & Private Equity","Veterinary","Warehousing","Wholesale","Wine and Spirits","Wireless","Writing and Editing"
              ]
  ADDITIONAL_INDUSTRY = [
                           "Accounting","Airlines/Aviation","Alternative Dispute Resolution","Alternative Medicine","Animation","Apparel & Fashion","Architecture & Planning","Arts and Crafts","Automotive","Aviation & Aerospace",
                           "Banking","Biotechnology","Broadcast Media","Building Materials","Business Supplies and Equipment",
                           "Capital Markets","Chemicals","Civic & Social Organization","Civil Engineering","Commercial Real Estate","Computer & Network Security","Computer Games","Computer Hardware",
                           "Computer Networking","Computer Software","Construction","Consumer Electronics","Consumer Goods","Consumer Services","Cosmetics",
                           "Dairy","Defense & Space","Design","Education Management","E-Learning","Electrical/Electronic Manufacturing","Entertainment","Environmental Services","Events Services","Executive Office",
                           "Facilities Services","Farming","Financial Services","Fine Art","Fishery","Food & Beverages","Food Production","Fund-Raising","Furniture",
                           "Gambling & Casinos","Glass, Ceramics & Concrete","Government Administration","Government Relations","Graphic Design",
                           "Health, Wellness and Fitness","Higher Education","Hospital & Health Care","Hospitality","Human Resources",
                           "Import and Export","Individual & Family Services","Industrial Automation","Information Services","Information Technology and Services","Insurance","International Affairs",
                           "International Trade and Development","Internet","Investment Banking","Investment Management","Judiciary",
                           "Law Enforcementaw Practice","Legal Services","Legislative Office","Leisure, Travel & Tourism","Libraries","Logistics and Supply Chain","Luxury Goods & Jewelry",
                           "Machinery","Management Consulting","Maritime","Marketing and Advertising","Market Research","Mechanical or Industrial Engineering","Media Production","Medical Devices",
                           "Medical Practice","Mental Health Care","Military","Mining & Metals","Motion Pictures and Film","Museums and Institutions","Music","Nanotechnology","Newspapers","Nonprofit Organization Management",
                           "Oil & Energy","Online Media","Outsourcing/Offshoring","Package/Freight Delivery","Packaging and Containers","Paper & Forest Products","Performing Arts","Pharmaceuticals","Philanthropy",
                           "Photography","Plastics","Political Organization","Primary/Secondary Education","Printing","Professional Training & Coaching","Program Development","Public Policy","Public Relations and Communications","Public Safety","Publishing",
                           "Railroad Manufacture","Ranching","Real Estate","Recreational Facilities and Services","Religious Institutions","Renewables & Environment","Research","Restaurants","Retail",
                           "Security and Investigations","Semiconductors","Shipbuilding","Sporting Goods","Sports","Staffing and Recruiting","Supermarkets","Telecommunications","Textiles","Think Tanks","Tobacco",
                           "Translation and Localization","Transportation/Trucking/Railroad","Utilities","Venture Capital & Private Equity","Veterinary","Warehousing","Wholesale","Wine and Spirits","Wireless","Writing and Editing"
   
                         ]
  WILLING_TO_RELOCATE = ["Yes", "No", "May be"]

  def upload_resume_or_linkedin_link
    if (self.linkedin_link.present? || self.resume.present?)
      return true
    else
      errors.add(:linkedin_link, " or Upload Resume, can't be blank! Must provide any one of this.")
    end
  end

  def total_experience
    "#{experience_in_years} years and #{experience_in_months} months"
  end
end

app/controllers/api/resumes_controller.rb
class Api::ResumesController < ApplicationController

  def index
    @resumes = Resume.all
    render json: @resumes
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  def index
    @resumes = Resume.all
  end

  def show;end

  def new
    @resume = Resume.new
    @resume.educations.new
    @resume.experiences.new
  end

  def edit;end

  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:name, :email, :phone, :reffered_by, :what_do_you_like, :willing_to_relocate, :preferred_location, :experience_in_years, :experience_in_months, :level, :industry, :additional_industry, :function, :linkedin_link, :resume, experiences_attributes: [:id, :title, :company, :location, :start_date, :end_date, :is_current, :description, :_destroy], educations_attributes: [:id, :university, :qualification, :year, :_destroy])
    end
end

app/helpers/api/resumes_helper.rb
module Api::ResumesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_education_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.label :university %>
    <%= f.text_field :university, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :qualification %>
    <%= f.text_field :qualification, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year, class: 'form-control' %>
  </div>

  <%= link_to_remove_association "remove education", f %>
</div>

app/views/resumes/_experience_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.text_field :end_date, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.check_box :is_current %>
    <%= f.label :is_current %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <%= link_to_remove_association "remove experience", f %>
</div>

app/views/resumes/_form.html.erb
<%= form_with(model: resume, local: true) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :resume_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :resume_email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :resume_phone, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :reffered_by %>
    <%= form.text_field :reffered_by, id: :resume_reffered_by, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :what_do_you_like %>
    <%= form.text_field :what_do_you_like, id: :resume_what_do_you_like, class: 'form-control' %>
  </div>

  <h3>Educations</h3>
  <div id='educations'>
    <%= form.fields_for :educations do |education| %>
      <%= render 'education_fields', f: education %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add education', form, :educations %>
    </div>
  </div>

  <h3>Qualifications</h3>
  <div id='experiences'>
    <%= form.fields_for :experiences do |experience| %>
      <%= render 'experience_fields', f: experience %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add experience', form, :experiences %>
    </div>
  </div>

  <div class="field">
    <%= form.label :willing_to_relocate %>
    <%= form.select :willing_to_relocate, options_for_select(Resume::WILLING_TO_RELOCATE, form.object.willing_to_relocate), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :preferred_location %>
    <%= form.text_field :preferred_location, id: :resume_preferred_location, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :experience_in_years %>
    <%= form.text_field :experience_in_years, id: :resume_experience_in_years, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :experience_in_months %>
    <%= form.text_field :experience_in_months, id: :resume_experience_in_months, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.select :level, options_for_select(Resume::LEVELS, form.object.level), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.select :industry, options_for_select(Resume::INDUSTRY, form.object.industry), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :additional_industry %>
    <%= form.select :additional_industry, options_for_select(Resume::ADDITIONAL_INDUSTRY, form.object.additional_industry), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :function %>
    <%= form.select :function, options_for_select(Resume::FUNCTIONS, form.object.function), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :linkedin_link %>
    <%= form.text_field :linkedin_link, id: :resume_linkedin_link, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :resume %>
    <%#= form.text_field :resume, id: :resume_resume, class: 'form-control' %>
    <%= form.filestack_field :resume, 'Upload Your Avatar!', id: 'unique-id', input_id: 'unique-input-id' %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit 'Submit', class: 'form-control' %>
  </div>
<% end %>

app/views/resumes/_main_form.html.erb
<%= form_with(model: resume, local: true) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :resume_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :resume_email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :resume_phone, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :reffered_by %>
    <%= form.text_field :reffered_by, id: :resume_reffered_by, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :what_do_you_like %>
    <%= form.text_field :what_do_you_like, id: :resume_what_do_you_like, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :willing_to_relocate %>
    <br>
    <% Resume::WILLING_TO_RELOCATE.each do |relocate, index| %>
      <%= radio_button_tag "resume[willing_to_relocate]", relocate %>
      <%= label_tag relocate %>
      <br>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :preferred_location %>
    <%= form.text_field :preferred_location, id: :resume_preferred_location, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :experience_in_years %>
    <%= form.text_field :experience_in_years, id: :resume_experience_in_years, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :experience_in_months %>
    <%= form.text_field :experience_in_months, id: :resume_experience_in_months, class: 'form-control' %>
  </div>

  <div class="field">
    <%= label_tag "What job level are you looking for?" %>
    <br>
    <% Resume::LEVELS.each_with_index do |level, index| %>
      <%= check_box_tag "resume[level][]", level %>
      <%= label_tag level %>
      <br>
    <% end  %>
  </div>
<!-- What kind of job are you targeting? -->
<!-- What is your ideal company size? -->
<!-- Where are you looking to be geographically located? -->
<!-- Deadline -->


  <div class="field">
    <%= form.label :industry %>
    <%= form.select :industry, options_for_select(Resume::INDUSTRY, form.object.industry), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :additional_industry %>
    <%= form.select :additional_industry, options_for_select(Resume::ADDITIONAL_INDUSTRY, form.object.additional_industry), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :function %>
    <%= form.select :function, options_for_select(Resume::FUNCTIONS, form.object.function), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :linkedin_link %>
    <%= form.text_field :linkedin_link, id: :resume_linkedin_link, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :resume %>
    <%#= form.text_field :resume, id: :resume_resume, class: 'form-control' %>
    <%= form.filestack_field :resume, 'Upload Your Resume!', id: 'unique-id', input_id: 'unique-input-id' %>
  </div>

  <h3>Educations</h3>
  <div id='educations'>
    <%= form.fields_for :educations do |education| %>
      <%= render 'education_fields', f: education %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add education', form, :educations %>
    </div>
  </div>

  <h3>Qualifications</h3>
  <div id='experiences'>
    <%= form.fields_for :experiences do |experience| %>
      <%= render 'experience_fields', f: experience %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add experience', form, :experiences %>
    </div>
  </div>

  <br>
  <div class="actions">
    <%= form.submit 'Submit', class: 'form-control' %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<div class="row resumes">
  <% @resumes.each do |resume| %>
    <div class="col-md-4 resume">
      <div class="name">
        <%= resume.name %>
      </div>
      <div class="title">
        <%= resume.experiences.current.title %>
        <span class="experience">
          <%= "Exp: #{resume.total_experience}" %>
        </span>
      </div>
      <div class="info">
        <%= "Works at #{resume.experiences.current.company} in #{resume.experiences.current.location}" %>  
      </div>
      <div class="education">
        <%= "Have done #{resume.educations.highest.qualification} from #{resume.educations.highest.university}" %>  
      </div>
      <div class="linkedin">
        <%= resume.linkedin_link %>
      </div>
      <div class="actions">
        <%#= link_to 'Show', resume %>
        <%= link_to 'Edit', edit_resume_path(resume) %>
        <%#= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<div class="page-content">
  <div class="top-section">
    <div class="content">
      <span>
        Tell us about yourself
        <br>
        We'll handle the rest
      </span>
      <p>
        We'll find matches for you in the network of Sequoia companies. Respond if you're interested. No Recruiter Spam. No hassles.
      </p>

      <%= image_tag "/assets/resume-page.png" %>

      <p>
        Get notified by the hiring team or directly from founders when an open role matches your profile.
      </p>
    </div>
  </div>

  <h1>Get Started</h1>

  <div class="form-section">   
    <div class="title">
      <h2>Profile Information</h2>
    </div> 
    <%= render 'main_form', resume: @resume %>
  </div>
</div>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resume.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resume.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resume.phone %>
</p>

<p>
  <strong>Reffered by:</strong>
  <%= @resume.reffered_by %>
</p>

<p>
  <strong>What do you like:</strong>
  <%= @resume.what_do_you_like %>
</p>

<p>
  <strong>Willing to relocate:</strong>
  <%= @resume.willing_to_relocate %>
</p>

<p>
  <strong>Preferred location:</strong>
  <%= @resume.preferred_location %>
</p>

<p>
  <strong>Experience in years:</strong>
  <%= @resume.experience_in_years %>
</p>

<p>
  <strong>Experience in months:</strong>
  <%= @resume.experience_in_months %>
</p>

<p>
  <strong>Level:</strong>
  <%= @resume.level %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @resume.industry %>
</p>

<p>
  <strong>Additional industry:</strong>
  <%= @resume.additional_industry %>
</p>

<p>
  <strong>Function:</strong>
  <%= @resume.function %>
</p>

<p>
  <strong>Linkedin link:</strong>
  <%= @resume.linkedin_link %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @resume.resume %>
</p>
<%#= filestack_image @resume.resume, transform: filestack_transform.resize(width:100, height:100).flip.enhance %>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>